//
// Generated file, do not edit! Created by opp_msgtool 6.0 from messageUpdate.msg.
//

#ifndef __MESSAGEUPDATE_M_H
#define __MESSAGEUPDATE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class MessageUpdate;
/**
 * Class generated from <tt>messageUpdate.msg:2</tt> by opp_msgtool.
 * <pre>
 * message MessageUpdate
 * {
 *     double value;
 * }
 * </pre>
 */
class MessageUpdate : public ::omnetpp::cMessage
{
  protected:
    double value = 0;

  private:
    void copy(const MessageUpdate& other);

  protected:
    bool operator==(const MessageUpdate&) = delete;

  public:
    MessageUpdate(const char *name=nullptr, short kind=0);
    MessageUpdate(const MessageUpdate& other);
    virtual ~MessageUpdate();
    MessageUpdate& operator=(const MessageUpdate& other);
    virtual MessageUpdate *dup() const override {return new MessageUpdate(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual double getValue() const;
    virtual void setValue(double value);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const MessageUpdate& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, MessageUpdate& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline MessageUpdate *fromAnyPtr(any_ptr ptr) { return check_and_cast<MessageUpdate*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __MESSAGEUPDATE_M_H

